# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170920_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetail',
            name='blog',
        ),
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.TextField(default='abc'),
        ),
        migrations.DeleteModel(
            name='BlogDetail',
        ),
    ]
